---
- name: install needed dependancies for Debian OS family
  apt: pkg=libc6-dev,python-setuptools,gcc,python-dev,sshpass state={{ ansible_pkg_state }}
  when: ansible_os_family in ['Debian','Linuxmint'] or ansible_os_family == 'Linuxmint'
  tags: ["packages","ansible"]

- name: Ensure pip is installed
  easy_install: name=pip
  tags: ["packages","ansible"]

- name: install ansible with pip
  pip: name=ansible state={{ ansible_pkg_state }}
  tags: ["packages","ansible"]
