---
- name: install needed dependancies for Debian OS family
  apt: pkg=python-pip,libc6-dev,gcc,python-dev state={{ ansible_pkg_state }}
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Linuxmint'
  tags: ["packages","ansible"]

- name: install ansible with pip
  pip: name=ansible state={{ ansible_pkg_state }}
  tags: ["packages","ansible"]